# Generated by Django 4.2.7 on 2023-12-01 15:16

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("STOCK", "STOCK"), ("INDEX", "INDEX")], max_length=100
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "market",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(db_index=True, max_length=100)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stocks",
                        to="stocks.market",
                    ),
                ),
            ],
            options={
                "db_table": "stock",
            },
        ),
        migrations.CreateModel(
            name="StockPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "price_open",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "price_close",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "price_high",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "price_low",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "price_change",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prices",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "db_table": "stock_price",
            },
        ),
        migrations.AddConstraint(
            model_name="stockprice",
            constraint=models.UniqueConstraint(
                fields=("stock", "date"), name="unique_stock_price_001"
            ),
        ),
    ]
