# Generated by Django 4.2.7 on 2023-12-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0002_index_indexprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexprice",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="stockprice",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name="indexprice",
            constraint=models.UniqueConstraint(
                fields=("index", "date"), name="unique_index_price_001"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockprice",
            constraint=models.UniqueConstraint(
                fields=("stock", "date"), name="unique_stock_price_001"
            ),
        ),
    ]
