# Generated by Django 4.2.7 on 2023-12-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0003_alter_indexprice_date_alter_stockprice_date_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="stockprice",
            index=models.Index(
                fields=["stock", "date"], name="stock_price_stock_i_334c7a_idx"
            ),
        ),
    ]
