# Generated by Django 4.2.7 on 2023-12-01 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0004_stockprice_stock_price_stock_i_334c7a_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="stockprice",
            name="stock_price_stock_i_334c7a_idx",
        ),
    ]
